### ISSUE TITLE
Can't get after 'artists'

### ISSUE THREAD

**Issue by Nekohime-San** [karlsander/spotify-url-info#36]
when i want to get the 'duration_ms' its say 'undefined'
`

-  disc_number: 1,
-   duration_ms: 180822,
-   explicit: false,
-   external_ids: { isrc: 'USRC11701901' },
-   external_urls:
-    { spotify: 'https://open.spotify.com/track/7vGuf3Y35N4wmASOKLUVVU' },
-   href: 'https://api.spotify.com/v1/tracks/7vGuf3Y35N4wmASOKLUVVU',
-   id: '7vGuf3Y35N4wmASOKLUVVU',
-   is_local: false,
-   is_playable: true,
-   name: 'Silence',
-   popularity: 80,
-   preview_url:
-    'https://p.scdn.co/mp3-preview/d779881bd6bbcced00dbf7f5b87e3374bf7c058b?cid=162b7dc01f3a4a2ca32ed3cec83d1e02',
-   track_number: 1,
-   type: 'track',
-   uri: 'spotify:track:7vGuf3Y35N4wmASOKLUVVU',
-   dominantColor: '#b6b6b6' }

`

**Comment by Nekohime-San** [comment]
a

**Comment by karlsander** [comment]
Did you figure your issue out?

**Comment by shem8** [comment]
@Nekohime-San why it was closed?
