### ISSUE TITLE
Only support 30 seconds of audio?

### ISSUE THREAD

**Issue by Adib-C** [karlsander/spotify-url-info#61]
So i just started using this package and idk if this is intended or not, but the audio link from `getPreview` is only about 30 seconds?

example:
```const { getPreview } = require("spotify-url-info");
const data = await getPreview('https://open.spotify.com/track/7eQvvCRBECiZoJkX3r6q1L')

console.log(data.audio)
```

I would get the audio link, but only 30 seconds long

**Comment by crxts** [comment]
Spotify only gives 30 seconds, but you can convert to youtube object by searching for `artist - title` and adding `"auto generated by YouTube"` to get a better match.
