### ISSUE TITLE
Can't find any data | Never works for me

### ISSUE THREAD

**Issue by pgamerxdev** [karlsander/spotify-url-info#63]
I keep getting this error again and again. Never works for me
My version is latest
![Screenshot 2020-12-04 at 11 18 06 AM](https://user-images.githubusercontent.com/71639879/101127784-463c1f80-3624-11eb-8099-cf5a145222b6.png)
My code is - 
```js
               const song = await getPreview(args[0])
               const songname = song.title
```

it gives error at line - `const song = await getPreview(args[0])`

How I defined - `var { getData, getPreview } = require("spotify-url-info");`

**Comment by crxts** [comment]
I have no trouble getting the info with exactly the same link, have you tried the getTracks method ?

**Comment by pgamerxdev** [comment]
Yep ! It gives error saying couldn't parse it or something

**Comment by crxts** [comment]
have you checked if args[0] gets the given link in full or if it's not set to lowercase ?

**Comment by pgamerxdev** [comment]
I checked 
It gives link only 
Problem is it works on https://runkit.com but not in my bot

**Comment by crxts** [comment]
args[0] is not in lowercase ? console.log to be sure

**Comment by pgamerxdev** [comment]
I did 
It's in lowercase

**Comment by crxts** [comment]
that's why you got an error, links are case sensitive

**Comment by pgamerxdev** [comment]
Ohhhh 
Lemme try it without changing it to lowercase

**Comment by pgamerxdev** [comment]
I tried ! Didn't work either

**Comment by pgamerxdev** [comment]
```js
   message.channel.send(`Searching for song ! We don't support spotify directly`)
                const args22 = message.content.slice(prefix.length).trim().split(/ +/g);
                const song = await getPreview(args22)
                console.log(args22)
                console.log(args22[0])
                const songname = song.title
                const search = await distube.search(songname)
                const firststep = search[0].url
                return distube.play(message, firststep)```
My code

**Comment by pgamerxdev** [comment]
I was being dumb 
Issue fixed
Thanks

**Comment by claude-6969** [comment]
@pgamerxdev how did you fix it?
