### ISSUE TITLE
Error: Couldn't find any data in embed page that we know how to parse

### ISSUE THREAD

**Issue by muhimur9049** [karlsander/spotify-url-info#65]
I seem to be getting this error for this one specific Spotify playlist link someone tried using. 

Spotify URL: https://open.spotify.com/playlist/4l5xMobcI9Ugg7MidB9vKR
Full error: https://srcb.in/r8xcmmZWsC

**Comment by muhimur9049** [comment]
Nvm seems to be fixed now after switching versions

**Comment by BlazeIsClone** [comment]
I'm getting the same error as well:
```
Error: Couldn't find any data in embed page that we know how to parse 
 at /mnt/d/Code/A41SLBot/node_modules/spotify-url-info/index.js:49:11 
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
my version: `"spotify-url-info": "^2.2.0",`
I clean installed the dependency aswell no luck.
