### ISSUE TITLE
getTracks() scrap limit?

### ISSUE THREAD

**Issue by henry-bao** [karlsander/spotify-url-info#67]
Hi, I have been using this package for my discord bot, and I realized that when I input a 300 songs playlist only the first 100 came back. Is that a limitation of this package or am I doing something wrong?

**Comment by karlsander** [comment]
Yep it's a limitation of the package. We are scraping the little spotify player embeds and they only load the first 100 tracks.

**Comment by karlsander** [comment]
I will amend the Readme with this so the next person will not have to wonder If their code is broken.

**Comment by henry-bao** [comment]
Thank you very much for the clarification
