### ISSUE TITLE
If a playlist having 100+ songs. It returns me only 100 songs details.

### ISSUE THREAD

**Issue by DynamoYT** [karlsander/spotify-url-info#69]
The url of the playlist: https://open.spotify.com/playlist/0TBIbASLrgYnrIUw5GpdZH?si=BfbrC08xTlehEgJ6GulPfg

**Comment by karlsander** [comment]
Yes, that is to be expected. We are scraping the spotify embed widget, and that only contains the first 100 tracks. I don't think there's anything we can do without adding another scraping method.
